logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

server:
  port: 8096

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon_db
    driver-class-name: org.postgresql.Driver
    username: youngseok
    password: dudtjr
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    generate-ddl: false
    open-in-view: false


